# GNU Make solution makefile autogenerated by Premake
# Type "make help" for usage help

ifndef config
  config=release
endif
export config

PROJECTS := core ckwc ckw

.PHONY: all clean help $(PROJECTS)

all: $(PROJECTS)

core: 
	@echo "==== Building core ($(config)) ===="
	@${MAKE} --no-print-directory -C . -f core.make

ckwc: core
	@echo "==== Building ckwc ($(config)) ===="
	@${MAKE} --no-print-directory -C . -f ckwc.make

ckw: core
	@echo "==== Building ckw ($(config)) ===="
	@${MAKE} --no-print-directory -C . -f ckw.make

clean:
	@${MAKE} --no-print-directory -C . -f core.make clean
	@${MAKE} --no-print-directory -C . -f ckwc.make clean
	@${MAKE} --no-print-directory -C . -f ckw.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "   release"
	@echo "   debug"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   core"
	@echo "   ckwc"
	@echo "   ckw"
	@echo ""
	@echo "For more information, see http://industriousone.com/premake/quick-start"
